// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AssignmentManagerContext))]
    partial class AssignmentManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletionPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5916ef2d-2075-44dc-a070-fa34a161f4cc"),
                            AssigneeId = new Guid("1e547cab-dbed-41aa-95c9-4afc3ba183a4"),
                            CompletionPercent = 100,
                            Deadline = new DateTime(2020, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Create project's GitHub repo.",
                            Name = "Setup project",
                            Priority = 2,
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("e60bc80c-21bb-481d-b248-34f6ebfea153"),
                            AssigneeId = new Guid("1e547cab-dbed-41aa-95c9-4afc3ba183a4"),
                            CompletionPercent = 45,
                            Deadline = new DateTime(2020, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Design high-level architecture of the project.",
                            Name = "Design system architecture",
                            Priority = 4,
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("30e00597-cf30-4430-8899-ce43a9f91702"),
                            AssigneeId = new Guid("1e547cab-dbed-41aa-95c9-4afc3ba183a4"),
                            CompletionPercent = 0,
                            Deadline = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Research and decide on unit test and mocking framework.",
                            Name = "Prepare for Unit Tests",
                            Priority = 3,
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("01e37ff1-cf73-4602-9816-cf0753a42fb4"),
                            AssigneeId = new Guid("1e547cab-dbed-41aa-95c9-4afc3ba183a4"),
                            CompletionPercent = 100,
                            Deadline = new DateTime(2020, 5, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Perform review of available software storage solutions.",
                            Name = "Review storage solutions",
                            Priority = 1,
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("87d0cf39-219e-49e2-9d73-167b8bd19f4d"),
                            AssigneeId = new Guid("1e547cab-dbed-41aa-95c9-4afc3ba183a4"),
                            CompletionPercent = 75,
                            Deadline = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Improve performance of software that is developed.",
                            Name = "Performance improvements",
                            Priority = 4,
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("894f91e1-2a0a-40a6-962d-cbe518deefe6"),
                            AssigneeId = new Guid("07d28657-02a1-47ad-be2f-7d0e0b4e45b1"),
                            CompletionPercent = 100,
                            Deadline = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Create plan of automated testing of developed systems.",
                            Name = "Automated testing plan",
                            Priority = 2,
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f7600c74-4eb0-41ac-9eff-4ff01a72c2b4"),
                            AssigneeId = new Guid("07d28657-02a1-47ad-be2f-7d0e0b4e45b1"),
                            CompletionPercent = 50,
                            Deadline = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Perform functional testing of developed system.",
                            Name = "Functional testing",
                            Priority = 3,
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("961881bc-fa7e-419f-968e-f852792c51d4"),
                            Description = "Tiny project with small development team.",
                            Name = "Project A"
                        },
                        new
                        {
                            Id = new Guid("4d56d43a-092b-4023-82e0-870484a1223d"),
                            Description = "Medium project with average development team.",
                            Name = "Project B"
                        },
                        new
                        {
                            Id = new Guid("86e85a6d-2a0e-4964-a606-3680985888a7"),
                            Description = "Large project with big development team.",
                            Name = "Project C"
                        });
                });

            modelBuilder.Entity("DAL.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowEmailNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33293875-ab05-495d-8883-8c23bfb66c2c"),
                            AllowEmailNotifications = false,
                            FirstName = "Andrey",
                            LastName = "Andrienko",
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d")
                        },
                        new
                        {
                            Id = new Guid("546c8c7c-4a94-464b-8cc7-fffb35bb0d29"),
                            AllowEmailNotifications = true,
                            FirstName = "Bogdan",
                            LastName = "Bogdanov",
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d")
                        },
                        new
                        {
                            Id = new Guid("1e547cab-dbed-41aa-95c9-4afc3ba183a4"),
                            AllowEmailNotifications = true,
                            FirstName = "Artem",
                            LastName = "Chepak",
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d")
                        },
                        new
                        {
                            Id = new Guid("07d28657-02a1-47ad-be2f-7d0e0b4e45b1"),
                            AllowEmailNotifications = true,
                            FirstName = "Sergey",
                            LastName = "Sergeev",
                            ProjectId = new Guid("4d56d43a-092b-4023-82e0-870484a1223d")
                        });
                });

            modelBuilder.Entity("DAL.Entities.Assignment", b =>
                {
                    b.HasOne("DAL.Entities.UserProfile", "Assignee")
                        .WithMany("IssuedAssignments")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.Project", b =>
                {
                    b.HasOne("DAL.Entities.UserProfile", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("DAL.Entities.UserProfile", b =>
                {
                    b.HasOne("DAL.Entities.Project", "Project")
                        .WithMany("Users")
                        .HasForeignKey("ProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
